### ISSUE TITLE
sysdump: Collect logs from cilium-node-init pods

### ISSUE THREAD

**Issue by pchaigno** [cilium/cilium-cli#1192]
We have logs for the Cilium agents but seem to be missing the logs for cilium-node-init pods.

**Comment by ioandr** [comment]
Hi @pchaigno is this issue still relevant? If yes I would like to take a stab on it.

First, I took a quick look at [sysdump.go](https://github.com/cilium/cilium-cli/blob/main/sysdump/sysdump.go) to understand how `cilium sysdump` collects and dumps info for Cilium.

Then, I tried to understand what "node init" means in the context of Cilium. I found the following references related to enabling node init via Helm:
- ServiceAccount: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L66
- DaemonSet: https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml#L2410

My understanding is that when Cilium is configured with node init, it runs a startup script on every cluster node; and it does so via the `cilium-node-init` DaemonSet. The underlying `node-init` containers are rather privileged and eventually run with the following image:
```yaml
  image:
    ...
    repository: "quay.io/cilium/startup-script"
    tag: "62093c5c233ea914bfa26a10ba41f8780d9b737f"
    ...
```

To solve this issue we have to extend [sysdump.go](https://github.com/cilium/cilium-cli/blob/main/sysdump/sysdump.go) in order to gather logs from the `node-init` container of every Pod of the `cilium-node-init` DaemonSet.

If the above description is accurate I can proceed with the implementation. Any pointers or feedback on the above are much appreciated!

**Comment by ioandr** [comment]
After some trial and error I found out that the `cilium` CLI performs some checks regarding node init in order to generate the DaemonSet:

https://github.com/cilium/cilium-cli/blob/main/install/node_init.go

I managed to enable Cilium node init in my kind cluster in two different ways: 

1. Deploy Cilium with `cilium install` after building a custom `cilium` CLI that modifies the `needsNodeInit()` to always return `true`
2. Deploy Cilium with `helm install ... --set nodeinit.enabled=true`

```
➜  cilium git:(main) kubectl get pods -n kube-system -l app.kubernetes.io/name=cilium-node-init
NAME                     READY   STATUS    RESTARTS   AGE
cilium-node-init-7x7g4   1/1     Running   0          9m43s
cilium-node-init-vkvjn   1/1     Running   0          9m43s
```

and

```
➜  cilium git:(main) kubectl logs -n kube-system ds/cilium-node-init                           
Found 2 pods, using pod/cilium-node-init-7x7g4
...

Node initialization complete
!!! startup-script succeeded!

```

In any case this does not matter much as long as we have a standard way to deploy Cilium with node init for development purposes. However I did not find any relevant documentation around this feature - which I understand is useful for specific versions and cloud providers.

**Comment by ioandr** [comment]
After running `cilium sysdump` locally I ended up with a `cilium-sysdump-*.zip` file which *does contain* logs for the `cilium-node-init` Pods:

```
➜  cilium git:(main) ✗ unzip -l cilium-sysdump-20230623-015427.zip | grep node-init  
      434  2023-06-23 01:54   cilium-sysdump-20230623-015427/logs-cilium-mqqnb-wait-for-node-init-20230623-015427.log
      124  2023-06-23 01:54   cilium-sysdump-20230623-015427/logs-cilium-nldnq-wait-for-node-init-20230623-015427.log
     2104  2023-06-23 01:54   cilium-sysdump-20230623-015427/logs-cilium-node-init-7x7g4-node-init-20230623-015427.log
     2104  2023-06-23 01:54   cilium-sysdump-20230623-015427/logs-cilium-node-init-vkvjn-node-init-20230623-015427.log
```

IIUC this is due to https://github.com/cilium/cilium-cli/blob/main/sysdump/sysdump.go#L1912:

```go
// SubmitLogsTasks submits tasks to collect kubernetes logs from pods.
func (c *Collector) SubmitLogsTasks(pods []*corev1.Pod, since time.Duration, limitBytes int64) error {
```

If this is the case, I am not sure why we need to explicitly retrieve logs from the `cilium-node-init` Pods (like the tool already does for Cilium Pods, Cilium Operator Pods, etc.).

Finally, what is actually missing from the sysdump is the YAML manifests of the node init DaemonSet and ServiceAccount (if present). Thoughts?

CC @pchaigno

**Comment by ioandr** [comment]
As a reference point I filed a PR that does the following:

* Adds a dedicated task to collect logs from the Cilium Node Init Pods
* Adds a dedicated task to collect the Cilium Node Init DaemonSet manifest (if present)
