### ISSUE TITLE
Cilium CLI should implement a standard way to restart all Cilium services

### ISSUE THREAD

**Issue by asauber** [cilium/cilium-cli#1513]
## Proposal / RFE

**Is your feature request related to a problem?**

There is currently no standard way to restart all Cilium services. Most pods are annotated with `app.kubernetes.io/part-of=cilium`. However, not everything is, such as `clustermesh-apiserver`. (per conversations on Slack, it should be, and will be at some point soon)

**Describe the solution you'd like**

The proposal is that a subcommand be added to the CLI which allows restarting Cilium as a complete system. The typical command used for resources in kubernetes is `kubectl rollout restart <resource>` e.g. `kubectl rollout restart deployment/myapp`. We could start with a simpler `cilium restart` command, or include this implementation in a `cilium rollout` subcommand, which might include `cilium rollout undo` as well.

This restart command could include some logic with regards to the order in which restarts are performed to aim for stability or "speed of restart" metrics.

**Comment by michi-covalent** [comment]
➕ for `cilium restart`. not sure if i want to introduce "rollout" concept.

**Comment by christarazi** [comment]
I think I'd be careful regarding

> This restart command could include some logic with regards to the order in which restarts are performed to aim for stability

because that may hide dependencies over time and if someone decides to restart Cilium components outside of this tool, they may run into problems. From a project point of view, I don't think we want to encode this if we don't need it, and I don't think we really do need it. Today, the only "dependency" is that the Agent waits for the Operator to install the CRDs. I'm not aware of any of dependency.

**Comment by asauber** [comment]
I see. Yes, it would be ideal to maintain proper order-independence.
