### ISSUE TITLE
Unable to set podCidr

### ISSUE THREAD

**Issue by rookie-z** [cilium/cilium-cli#2171]
Unable to set podCidr, when I set its value through parameters, I only get its default value of 10.0.0.0/8

![image](https://github.com/cilium/cilium-cli/assets/47766331/dc8fa638-6a8f-4931-8441-234e4fd2889e)
![image](https://github.com/cilium/cilium-cli/assets/47766331/82ef76f3-c1a9-4ac8-8dfa-51c887e843e7)
![image](https://github.com/cilium/cilium-cli/assets/47766331/19f9b6d5-47c6-43fc-9189-b4e20eefc611)

cilium-cli  install --set ipam.operator.clusterPoolIPv4PodCIDRList=10.20.0.0/16
cilium-cli  install --set  cluster-pool-ipv4-cidr=10.20.0.0/16
cilium-cli  install --set  cluster.pool.ipv4.cidr=10.20.0.0/16
The default values will not be changed through its parameters and other parameter settings, and changing the values in kubernetes configMap will not be successful either

**Comment by stepanovdg** [comment]
@rookie-z 
Struggled with that almost all day - there changed syntax
now it is 
cilium install --set=ipam.operator.clusterPoolIPv4PodCIDRList=172.29.0.0/16,otherConfigs...

**Comment by rookie-z** [comment]
@stepanovdg 
Thank you.

**Comment by xyzst** [comment]
> [@rookie-z](https://github.com/rookie-z) Struggled with that almost all day - there changed syntax now it is cilium install --set=ipam.operator.clusterPoolIPv4PodCIDRList=172.29.0.0/16,otherConfigs...

fyi: this helped me resolve my own issue with customizing the CIDR list, but it has changed since then

as of cilium-cli (v1.16.3), this is the formatting that is documented in `cilium help install`:

```
 cilium install --set ipam.operator.clusterPoolIPv4PodCIDRList=10.10.0.0/16 --set key=value
```

This particular configuration accepts a list of CIDR values, so it appears a comma separated list of values would be acceptable as such:

```
 cilium install --set ipam.operator.clusterPoolIPv4PodCIDRList=10.10.0.0/16,10.11.0.0/16 --set key=value
```

(i didn't test the second command or inspect code to verify)

list of values that can be set is provided here -- https://docs.cilium.io/en/stable/helm-reference/
