### ISSUE TITLE
 Implementing multicast connectivity test

### ISSUE THREAD

**Issue by yushoyamaguchi** [cilium/cilium-cli#2615]
## Proposal / RFE

We would like to implement a connectivity test for multicast.

https://github.com/cilium/cilium-cli/issues/2574

**Comment by yushoyamaguchi** [comment]
Some questions:
- How should we prepare a container image by which we can use IGMP and multicast compatibility check tool (iperf2 etc...).
- Is it allowed to create a test scenario which affects the state of cilium-agent
    - In multicast, remote-node must be registered as an agent to achieve communication.
- Is it allowed to create a test scenario which check the contents of stdout
    - It's hard to determine by the exit code of the command because you can't receive a reply via multicast.

**Comment by harsimran-pabla** [comment]
> To what extent Multicast E2E test is required ?
You definitely want it, or you'll review it if you can afford it ?

We would definitely want it since more functionality is being added to cilium bpf code and cilium-cli,
it is natural that we want some sort of automated testing to ensure that there is no regression
introduced.

There are couple of incentives to get these tests completed sooner rather than later:
- Before we introduce any new functionality to existing multicast implementation (cli or bpf), we should
get e2e tests first.
- In order to move this feature out of beta, we need to have e2e tests.

Personally, I will be happy to review the changes as well as provide feedback on proposed test scenarios.

**Comment by harsimran-pabla** [comment]
> How should we prepare a container image by which we can use both IGMP and multicast communication check tool(s) ?

Consider using https://github.com/nicolaka/netshoot container. You can use the `socat` utility to send and receive multicast packets; it will also send IGMP to join/leave messages. 

http://www.dest-unreach.org/socat/doc/socat-multicast.html

**Comment by harsimran-pabla** [comment]
> Is it allowed to create a test scenario which affects the state of cilium-agent?

I am not sure if I understand this correctly, cilium agent state is modified by CLIs; is there any other state change you have in mind?

I'd say define the test cases, and we can go over the details of such scenarios.

**Comment by yushoyamaguchi** [comment]
@harsimran-pabla 
Thank you for your comment.
I'll start implementation using socat.

Regarding the third concern, in APAC Dev MTG,  I was told that as long as I do the clean up properly, I can put the settings in cilium-agent for testing purposes.
