### ISSUE TITLE
GKE cleanup fails

### ISSUE THREAD

**Issue by jrajahalme** [cilium/cilium-cli#445]
```
Run gcloud container clusters delete cilium-cilium-cli-1046557892-vm --zone us-west2-a --quiet --async
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ["ResponseError: code=404, message=Not found: projects/***/zones/us-west2-a/clusters/cilium-cilium-cli-1046557892-vm.\nNo cluster named 'cilium-cilium-cli-1046557892-vm' in ***."]
   exit_code: 1

ERROR: (gcloud.compute.instances.delete) Could not fetch resource:
 - The resource 'projects/***/zones/us-west2-a/instances/cilium-cilium-cli-1046557892-vm' was not found
 ```
 Looks like a VM is trying to be deleted as a cluster? Or maybe a delete that can't find a resource should not fail the test?
 
 https://github.com/cilium/cilium-cli/pull/444/checks?check_run_id=3107899715

**Comment by nbusseneau** [comment]
The issue here is that the GCP VM failed to create:
```
Run gcloud compute instances create cilium-cilium-cli-1046557892-vm \
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/***/regions/us-west2/subnetworks/default' is not ready
```
The workflow then stopped and there was nothing to clean up because neither the VM nor the cluster were created.

This is known flake: I had tried to fix that in #338 but was unsuccessful. At least having the setup reversed makes it a bit more reliable when tearing down (as cluster deletion is asynchronous, it was causing more issues the other way around).

From GCP documentation, this comes from simultaneous resource operations (https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation) however we have no control over that. Their only recommendation is to add retries. I think we should do that considering it's an infrastructure issue and it also is easily contained to the GCP VM creation step.

But I haven't gotten around to it yet xD
Since we hadn't tracked this in an issue, I propose we repurpose this one if that's OK with you.

PS: I recommend to use permanent Actions links, and not the Check links which are temporary and disappear when checks are refreshed (see non-working link in OP). Permanent links look this:
- https://github.com/cilium/cilium-cli/actions/runs/1046557892
- https://github.com/cilium/cilium-cli/runs/3107899715?check_suite_focus=true

You can find the permanent links either by:
- Clicking on the workflow name from the Checks page.
- Finding the workflow run from the Actions tab (can be filtered by workflow / branch / event).

**Comment by pchaigno** [comment]
> From GCP documentation, this comes from simultaneous resource operations (https://cloud.google.com/compute/docs/troubleshooting/troubleshooting-vm-creation) however we have no control over that.

Between the cluster deletion and the subsequent VM creation? Do we really need to make the cluster deletion asynchronous? IIRC, it's pretty fast on GKE anyway.

> PS: I recommend to use permanent Actions links, and not the Check links which are temporary and disappear when checks are refreshed (see non-working link in OP). 

I don't think a lot of contributors are aware of this. Maybe worth mentioning it in other venues (calls & Slack)?

**Comment by nbusseneau** [comment]
> Between the cluster deletion and the subsequent VM creation? Do we really need to make the cluster deletion asynchronous? IIRC, it's pretty fast on GKE anyway.

No, it can conflict with any operation running on GCP at the same time (another workflow, etc.). Anything you do in GCP is actually always asynchronous even when it looks like it synchronous, because what most commands do is call the operations API and log a new operation (check out `gcloud container operations list` if you're curious) and then wait for that operation to end.

> I don't think a lot of contributors are aware of this. Maybe worth mentioning it in other venues (calls & Slack)?

Already did on both 😁

**Comment by nbusseneau** [comment]
@michi-covalent The fix in action: https://github.com/cilium/cilium-cli/actions/runs/1102850699

- Adds warnings in the logs:
```
Run nick-invision/retry@45ba062d357edb3b29c4a94b456b188716f61020

WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/***/regions/us-west2/subnetworks/default' is not ready

Warning: Attempt 1 failed. Reason: Child_process exited with error code 1

WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/***/regions/us-west2/subnetworks/default' is not ready

Warning: Attempt 2 failed. Reason: Child_process exited with error code 1

WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
Created [https://www.googleapis.com/compute/v1/projects/***/zones/us-west2-a/instances/cilium-cilium-cli-1102850699-vm].
NAME                             ZONE        MACHINE_TYPE                   PREEMPTIBLE  INTERNAL_IP   EXTERNAL_IP     STATUS
cilium-cilium-cli-1102850699-vm  us-west2-a  custom (e2, 2 vCPU, 4.00 GiB)  true         10.168.0.109  34.102.118.172  RUNNING
Command completed after 3 attempt(s).
```
- Even adds warnings directly on the workflow run page. Nice!
