### ISSUE TITLE
cilium hubble enable has incorrect sha for hubble-relay

### ISSUE THREAD

**Issue by joebowbeerxealth** [cilium/cilium-cli#456]
I'm running `cilium hubble enable` on a cluster with cilium installed (via helm)

Expected: hubble-relay running
Actual: hubble-relay pending

Reason: The sha256 (8419531) for hubble-relay does not match the sha26 in quay.io

Note: The sha256 matches the cilium image not the hubble-relay image.

Workarounds: 
```
cilium hubble enable --relay-version v1.10.3@sha256:af8ff09fe374c307356a85b0e0c158359a2e7299f93280151301b7f2fac27339
```

```
cilium hubble enable --relay-version v1.10.3
```

Repro:

```
cilium hubble enable --ui
🔑 Found existing CA in secret cilium-ca
✨ Patching ConfigMap cilium-config to enable Hubble...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
🔑 Generating certificates for Relay...
2021/07/28 11:11:24 [INFO] generate received request
2021/07/28 11:11:24 [INFO] received CSR
2021/07/28 11:11:24 [INFO] generating key: ecdsa-256
2021/07/28 11:11:24 [INFO] encoded CSR
2021/07/28 11:11:24 [INFO] signed certificate with serial number 413427939379873309990048170079931144382015256457
2021/07/28 11:11:24 [INFO] generate received request
2021/07/28 11:11:24 [INFO] received CSR
2021/07/28 11:11:24 [INFO] generating key: ecdsa-256
2021/07/28 11:11:24 [INFO] encoded CSR
2021/07/28 11:11:24 [INFO] signed certificate with serial number 81632895871174633518388009116993590397723020795
✨ Deploying Relay from quay.io/cilium/hubble-relay:v1.10.3@sha256:8419531c5d3677158802882bdfe2297915c43f2ebe3649551aaac22de9f6d565...
✨ Deploying Hubble UI...
✅ Hubble was successfully enabled!
```

```
cilium status
quay.io/cilium/hubble-relay:v1.10.3@sha256:8419531c5d3677158802882bdfe2297915c43f2ebe3649551aaac22de9f6d565: 1
Errors:           hubble-relay       hubble-relay                    1 pods of Deployment hubble-relay are not ready
Warnings:         hubble-relay       hubble-relay-b46fff564-gm6z7    pod is pending
```

**Comment by gandro** [comment]
Thanks for the report. Looking at this, it seems the problem is that `cilium hubble enable` and `cilium clustermesh enable` re-use the sha256 from the Cilium image, which of course is wrong. 

Uses of `cilium install` will not use a sha256, so this currently only occurs if the user installed Cilium via Helm.

There are two steps in fixing this:
1. Do not reuse the sha256 from the Cilium version (easy, I will open a PR for this)
2. Determine the correct sha256 somehow (harder, and probably also should apply to `cilium install --version v1.10.x`). 

We should probably open a separate tracking issue for the latter, as I think it needs quite some additional logic.

**Comment by gandro** [comment]
> Any chance of cilium-cli being able to install Cilium chained to eks-vpc-cni? Currently, helm is the only documented method.

I don't think we support that currently in the CLI. I recommend opening a new feature request issue for that.

Note that, if possible, we recommend using Helm to enable Hubble if Cilium was installed via Helm, see the `Helm` tab in https://docs.cilium.io/en/v1.10/gettingstarted/hubble_setup/#hubble-setup
