### ISSUE TITLE
CI: GKE-based: network "default" does not have available private IP space in 10.0.0.0/8 to reserve a /14 block

### ISSUE THREAD

**Issue by tklauser** [cilium/cilium-cli#940]
GKE-based workflows (GKE, external workloads, multicluster) occasionally fail during cluster creation with the following error:

```
The network "default" does not have available private IP space in 10.0.0.0/9 to reserve a /14 block for pods for cluster 
``` 

Examples:
* Scheduled run on `master`: https://github.com/cilium/cilium-cli/runs/7000764590?check_suite_focus=true
* PR #933: https://github.com/cilium/cilium-cli/runs/6993592366?check_suite_focus=true

I assume this can happen if too many clusters are created simultaneously. One option to work around this would be to specify `--cluster-ipv4-cider` on `gcloud container clusters create`. Also see https://stackoverflow.com/questions/42129327/gke-cluster-creation-fails-because-the-network-default-does-not-have-available

**Comment by margamanterola** [comment]
The runs linked by Tobias have now expired, but here's a recent one (from the cilium repo) that has the same error message: https://github.com/cilium/cilium/actions/runs/3464773077/jobs/5786716112

https://github.com/cilium/cilium/actions/workflows/conformance-gke.yaml is currently disabled because how flaky it is.

CC: @brlbil
